### ISSUE TITLE
Possible implementation inside Cruise Industry 

### ISSUE THREAD

**Issue by ansuff** [GiovanniGatti/talos#1]
Hi,

I found this paper with the codebase while researching RL for our RMS system. However, there are many adjustments needed before starting such research. Can this work be adapted for the cruise industry?

Thanks,
Anas

**Comment by GiovanniGatti** [comment]
Hello @ansuff,

I'm not familiar with the Curise industry challenges, but this project tackles fundamental problems that applies to all RMSs.

The tech stack here is quite old. RLLib changed so much since we published this. If you are starting research on this direction, I advise you to start it a new training pipeline and copy&paste only the useful code.

I hope this helps.

**Comment by ansuff** [comment]
Hey @GiovanniGatti,

Thanks for your quick response.

I noticed some parts of the codebase are outdated due to significant changes in the last two years.

I’m currently trying RL in my company, but it seems too complex for the cruise industry with many undocumented variables.

I hope my research is useful. You never know, I might open a PR to yours.

Best,
Anas

**Comment by GiovanniGatti** [comment]
Hey @ansuff,

If you wish we can meet so you can share a bit more on your needs. I can help pointing out what might be useful in your use case. I can also provide you more insights on this project. 

Lastly, you might want to check in my PhD thesis: https://theses.hal.science/tel-03982091/file/2022COAZ4047.pdf

It is long material true, but it was built to facilitate the entry on the topic of what's possible to do with RL in RMS. You will find more insights, experiments and crazy dreams I had back on old days. It contains a many reflections of research directions and ideas of things to try.

Honestly, if I were to start today in a different industry, I would go straight for the solution described in Section 5.3 (you will need to read the whole Chapter 5 to understand it). 

From the more tactical aspect, I would drop the LSTM choice. It made sense on the time, but I suggest going straight to a Transformer architecture. That said, you don't have much to reuse from this old project, except perhaps the environment model implementation (unless yours does not follow the same set of rules).

**Comment by ansuff** [comment]
Meeting would be great. I’ll also review your implementation in your PhD thesis. I’m not an expert in RL, but I’m certain the cruise industry can greatly benefit from it, given the many restrictions and rules.

Where should we meet? I can share a Teams meeting. Let me know your preferred time and email address for the invite.

Thanks again for your responses. I look forward to meeting you.

**Comment by GiovanniGatti** [comment]
Hey, I sent you an invite on LinkedIn. Let's continue this discussion through private means.
